version: "3.8"

services:
  app:
    build:
      context: "./"
      dockerfile: "./docker/fastapi/Dockerfile"
    image: "registry.digitalocean.com/brbcoffee/site:subs"
    ports:
      - "80:80"
      - "5678:5678"
      - "3000:3000"
